using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsLT()
    {
        AddSubdivisions("LT", new List<Subdivision>()
        {
            new(){ Code ="41", LocalName="akiai", Name="akiai", Type="Municipality" },
            new(){ Code ="42", LocalName="alcininkai", Name="alcininkai", Type="Municipality" },
            new(){ Code ="44", LocalName="iauliai", Name="iauliai", Type="Municipality" },
            new(){ Code ="SA", LocalName="iauliu Apskritis", Name="iauliu Apskritis", Type="County" },
            new(){ Code ="43", LocalName="iauliu miestas", Name="iauliu miestas", Type="Municipality" },
            new(){ Code ="45", LocalName="ilale", Name="ilale", Type="Municipality" },
            new(){ Code ="46", LocalName="ilute", Name="ilute", Type="Municipality" },
            new(){ Code ="47", LocalName="irvintos", Name="irvintos", Type="Municipality" },
            new(){ Code ="49", LocalName="vencionys", Name="vencionys", Type="Municipality" },
            new(){ Code ="1", LocalName="Akmene", Name="Akmene", Type="Municipality" },
            new(){ Code ="AL", LocalName="Alytaus Apskritis", Name="Alytaus Apskritis", Type="County" },
            new(){ Code ="2", LocalName="Alytaus miestas", Name="Alytaus miestas", Type="Municipality" },
            new(){ Code ="3", LocalName="Alytus", Name="Alytus", Type="Municipality" },
            new(){ Code ="4", LocalName="Anykciai", Name="Anykciai", Type="Municipality" },
            new(){ Code ="6", LocalName="Birai", Name="Birai", Type="Municipality" },
            new(){ Code ="5", LocalName="Birtono", Name="Birtono", Type="Municipality" },
            new(){ Code ="7", LocalName="Druskininkai", Name="Druskininkai", Type="Municipality" },
            new(){ Code ="8", LocalName="Elektrénai", Name="Elektrénai", Type="Municipality" },
            new(){ Code ="9", LocalName="Ignalina", Name="Ignalina", Type="Municipality" },
            new(){ Code ="10", LocalName="Jonava", Name="Jonava", Type="Municipality" },
            new(){ Code ="11", LocalName="Jonikis", Name="Jonikis", Type="Municipality" },
            new(){ Code ="12", LocalName="Jurbarkas", Name="Jurbarkas", Type="Municipality" },
            new(){ Code ="13", LocalName="Kaiiadorys", Name="Kaiiadorys", Type="Municipality" },
            new(){ Code ="14", LocalName="Kalvarijos", Name="Kalvarijos", Type="Municipality" },
            new(){ Code ="16", LocalName="Kaunas", Name="Kaunas", Type="Municipality" },
            new(){ Code ="KU", LocalName="Kauno Apskritis", Name="Kauno Apskritis", Type="County" },
            new(){ Code ="15", LocalName="Kauno miestas", Name="Kauno miestas", Type="Municipality" },
            new(){ Code ="17", LocalName="Kazlu Rudos", Name="Kazlu Rudos", Type="Municipality" },
            new(){ Code ="18", LocalName="Kedainiai", Name="Kedainiai", Type="Municipality" },
            new(){ Code ="19", LocalName="Kelme", Name="Kelme", Type="Municipality" },
            new(){ Code ="21", LocalName="Klaipeda", Name="Klaipeda", Type="Municipality" },
            new(){ Code ="KL", LocalName="Klaipedos apskritis", Name="Klaipedos apskritis", Type="County" },
            new(){ Code ="20", LocalName="Klaipedos miestas", Name="Klaipedos miestas", Type="Municipality" },
            new(){ Code ="22", LocalName="Kretinga", Name="Kretinga", Type="Municipality" },
            new(){ Code ="23", LocalName="Kupikis", Name="Kupikis", Type="Municipality" },
            new(){ Code ="24", LocalName="Lazdijai", Name="Lazdijai", Type="Municipality" },
            new(){ Code ="26", LocalName="Maeikiai", Name="Maeikiai", Type="Municipality" },
            new(){ Code ="25", LocalName="Marijampole", Name="Marijampole", Type="Municipality" },
            new(){ Code ="MR", LocalName="Marijampoles apskritis", Name="Marijampoles apskritis", Type="County" },
            new(){ Code ="27", LocalName="Moletai", Name="Moletai", Type="Municipality" },
            new(){ Code ="28", LocalName="Neringa", Name="Neringa", Type="Municipality" },
            new(){ Code ="29", LocalName="Pagégiai", Name="Pagégiai", Type="Municipality" },
            new(){ Code ="30", LocalName="Pakruojis", Name="Pakruojis", Type="Municipality" },
            new(){ Code ="31", LocalName="Palangos miestas", Name="Palangos miestas", Type="Municipality" },
            new(){ Code ="PN", LocalName="Paneveio apskritis", Name="Paneveio apskritis", Type="County" },
            new(){ Code ="32", LocalName="Paneveio miestas", Name="Paneveio miestas", Type="Municipality" },
            new(){ Code ="33", LocalName="Paneveys", Name="Paneveys", Type="Municipality" },
            new(){ Code ="34", LocalName="Pasvalys", Name="Pasvalys", Type="Municipality" },
            new(){ Code ="35", LocalName="Plunge", Name="Plunge", Type="Municipality" },
            new(){ Code ="36", LocalName="Prienai", Name="Prienai", Type="Municipality" },
            new(){ Code ="37", LocalName="Radvilikis", Name="Radvilikis", Type="Municipality" },
            new(){ Code ="38", LocalName="Raseiniai", Name="Raseiniai", Type="Municipality" },
            new(){ Code ="39", LocalName="Rietavo", Name="Rietavo", Type="Municipality" },
            new(){ Code ="40", LocalName="Rokikis", Name="Rokikis", Type="Municipality" },
            new(){ Code ="48", LocalName="Skuodas", Name="Skuodas", Type="Municipality" },
            new(){ Code ="50", LocalName="Taurage", Name="Taurage", Type="Municipality" },
            new(){ Code ="TA", LocalName="Taurages apskritis", Name="Taurages apskritis", Type="County" },
            new(){ Code ="51", LocalName="Teliai", Name="Teliai", Type="Municipality" },
            new(){ Code ="TE", LocalName="Teliu Apskritis", Name="Teliu Apskritis", Type="County" },
            new(){ Code ="52", LocalName="Trakai", Name="Trakai", Type="Municipality" },
            new(){ Code ="53", LocalName="Ukmerge", Name="Ukmerge", Type="Municipality" },
            new(){ Code ="54", LocalName="Utena", Name="Utena", Type="Municipality" },
            new(){ Code ="UT", LocalName="Utenos Apskritis", Name="Utenos Apskritis", Type="County" },
            new(){ Code ="55", LocalName="Varena", Name="Varena", Type="Municipality" },
            new(){ Code ="56", LocalName="Vilkavikis", Name="Vilkavikis", Type="Municipality" },
            new(){ Code ="VL", LocalName="Vilniaus Apskritis", Name="Vilniaus Apskritis", Type="County" },
            new(){ Code ="57", LocalName="Vilniaus miestas", Name="Vilniaus miestas", Type="Municipality" },
            new(){ Code ="58", LocalName="Vilnius", Name="Vilnius", Type="Municipality" },
            new(){ Code ="59", LocalName="Visaginas", Name="Visaginas", Type="Municipality" },
            new(){ Code ="60", LocalName="Zarasai", Name="Zarasai", Type="Municipality" }

        });
    }
}
