using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsPH()
    {
        AddSubdivisions("PH", new List<Subdivision>()
        {
            new(){ Code ="ABR", LocalName="Abra", Name="Abra", Type="Province" },
            new(){ Code ="AGN", LocalName="Agusan del Norte", Name="Agusan del Norte", Type="Province" },
            new(){ Code ="AGS", LocalName="Agusan del Sur", Name="Agusan del Sur", Type="Province" },
            new(){ Code ="AKL", LocalName="Aklan", Name="Aklan", Type="Province" },
            new(){ Code ="ALB", LocalName="Albay", Name="Albay", Type="Province" },
            new(){ Code ="ANT", LocalName="Antique", Name="Antique", Type="Province" },
            new(){ Code ="APA", LocalName="Apayao", Name="Apayao", Type="Province" },
            new(){ Code ="AUR", LocalName="Aurora", Name="Aurora", Type="Province" },
            new(){ Code ="BAS", LocalName="Basilan", Name="Basilan", Type="Province" },
            new(){ Code ="BAN", LocalName="Bataan", Name="Bataan", Type="Province" },
            new(){ Code ="BTN", LocalName="Batanes", Name="Batanes", Type="Province" },
            new(){ Code ="BTG", LocalName="Batangas", Name="Batangas", Type="Province" },
            new(){ Code ="BEN", LocalName="Benguet", Name="Benguet", Type="Province" },
            new(){ Code ="BIL", LocalName="Biliran", Name="Biliran", Type="Province" },
            new(){ Code ="BOH", LocalName="Bohol", Name="Bohol", Type="Province" },
            new(){ Code ="BUK", LocalName="Bukidnon", Name="Bukidnon", Type="Province" },
            new(){ Code ="BUL", LocalName="Bulacan", Name="Bulacan", Type="Province" },
            new(){ Code ="CAG", LocalName="Cagayan", Name="Cagayan", Type="Province" },
            new(){ Code ="CAN", LocalName="Camarines Norte", Name="Camarines Norte", Type="Province" },
            new(){ Code ="CAS", LocalName="Camarines Sur", Name="Camarines Sur", Type="Province" },
            new(){ Code ="CAM", LocalName="Camiguin", Name="Camiguin", Type="Province" },
            new(){ Code ="CAP", LocalName="Capiz", Name="Capiz", Type="Province" },
            new(){ Code ="CAT", LocalName="Catanduanes", Name="Catanduanes", Type="Province" },
            new(){ Code ="CAV", LocalName="Cavite", Name="Cavite", Type="Province" },
            new(){ Code ="CEB", LocalName="Cebu", Name="Cebu", Type="Province" },
            new(){ Code ="COM", LocalName="Compostela Valley", Name="Compostela Valley", Type="Province" },
            new(){ Code ="DAV", LocalName="Davao del Norte", Name="Davao del Norte", Type="Province" },
            new(){ Code ="DAS", LocalName="Davao del Sur", Name="Davao del Sur", Type="Province" },
            new(){ Code ="DAO", LocalName="Davao Oriental", Name="Davao Oriental", Type="Province" },
            new(){ Code ="DIN", LocalName="Dinagat Islands", Name="Dinagat Islands", Type="Province" },
            new(){ Code ="EAS", LocalName="Eastern Samar", Name="Eastern Samar", Type="Province" },
            new(){ Code ="GUI", LocalName="Guimaras", Name="Guimaras", Type="Province" },
            new(){ Code ="IFU", LocalName="Ifugao", Name="Ifugao", Type="Province" },
            new(){ Code ="ILN", LocalName="Ilocos Norte", Name="Ilocos Norte", Type="Province" },
            new(){ Code ="ILS", LocalName="Ilocos Sur", Name="Ilocos Sur", Type="Province" },
            new(){ Code ="ILI", LocalName="Iloilo", Name="Iloilo", Type="Province" },
            new(){ Code ="ISA", LocalName="Isabela", Name="Isabela", Type="Province" },
            new(){ Code ="KAL", LocalName="Kalinga-Apayao", Name="Kalinga-Apayao", Type="Province" },
            new(){ Code ="DVO", LocalName="Kanlurang Dabaw", Name="Kanlurang Dabaw", Type="Province" },
            new(){ Code ="NCO", LocalName="Kotabato", Name="Kotabato", Type="Province" },
            new(){ Code ="LUN", LocalName="La Union", Name="La Union", Type="Province" },
            new(){ Code ="LAG", LocalName="Laguna", Name="Laguna", Type="Province" },
            new(){ Code ="LAN", LocalName="Lanao del Norte", Name="Lanao del Norte", Type="Province" },
            new(){ Code ="LAS", LocalName="Lanao del Sur", Name="Lanao del Sur", Type="Province" },
            new(){ Code ="LEY", LocalName="Leyte", Name="Leyte", Type="Province" },
            new(){ Code ="MAG", LocalName="Maguindanao", Name="Maguindanao", Type="Province" },
            new(){ Code ="MAD", LocalName="Marinduque", Name="Marinduque", Type="Province" },
            new(){ Code ="MAS", LocalName="Masbate", Name="Masbate", Type="Province" },
            new(){ Code ="MDC", LocalName="Mindoro Occidental", Name="Mindoro Occidental", Type="Province" },
            new(){ Code ="MDR", LocalName="Mindoro Oriental", Name="Mindoro Oriental", Type="Province" },
            new(){ Code ="MSC", LocalName="Misamis Occidental", Name="Misamis Occidental", Type="Province" },
            new(){ Code ="MSR", LocalName="Misamis Oriental", Name="Misamis Oriental", Type="Province" },
            new(){ Code ="MOU", LocalName="Mountain Province", Name="Mountain Province", Type="Province" },
            new(){ Code ="0", LocalName="National Capital Région", Name="National Capital Région", Type="Region" },
            new(){ Code ="NEC", LocalName="Negros occidental", Name="Negros occidental", Type="Province" },
            new(){ Code ="NER", LocalName="Negros oriental", Name="Negros oriental", Type="Province" },
            new(){ Code ="NSA", LocalName="Northern Samar", Name="Northern Samar", Type="Province" },
            new(){ Code ="NUE", LocalName="Nueva Ecija", Name="Nueva Ecija", Type="Province" },
            new(){ Code ="NUV", LocalName="Nueva Vizcaya", Name="Nueva Vizcaya", Type="Province" },
            new(){ Code ="PLW", LocalName="Palawan", Name="Palawan", Type="Province" },
            new(){ Code ="PAM", LocalName="Pampanga", Name="Pampanga", Type="Province" },
            new(){ Code ="PAN", LocalName="Pangasinan", Name="Pangasinan", Type="Province" },
            new(){ Code ="QUE", LocalName="Quezon", Name="Quezon", Type="Province" },
            new(){ Code ="QUI", LocalName="Quirino", Name="Quirino", Type="Province" },
            new(){ Code ="RIZ", LocalName="Rizal", Name="Rizal", Type="Province" },
            new(){ Code ="ROM", LocalName="Romblon", Name="Romblon", Type="Province" },
            new(){ Code ="SAR", LocalName="Sarangani", Name="Sarangani", Type="Province" },
            new(){ Code ="SIG", LocalName="Siquijor", Name="Siquijor", Type="Province" },
            new(){ Code ="SOR", LocalName="Sorsogon", Name="Sorsogon", Type="Province" },
            new(){ Code ="SCO", LocalName="South Cotabato", Name="South Cotabato", Type="Province" },
            new(){ Code ="SLE", LocalName="Southern Leyte", Name="Southern Leyte", Type="Province" },
            new(){ Code ="SUK", LocalName="Sultan Kudarat", Name="Sultan Kudarat", Type="Province" },
            new(){ Code ="SLU", LocalName="Sulu", Name="Sulu", Type="Province" },
            new(){ Code ="SUN", LocalName="Surigao del Norte", Name="Surigao del Norte", Type="Province" },
            new(){ Code ="SUR", LocalName="Surigao del Sur", Name="Surigao del Sur", Type="Province" },
            new(){ Code ="TAR", LocalName="Tarlac", Name="Tarlac", Type="Province" },
            new(){ Code ="TAW", LocalName="Tawi-Tawi", Name="Tawi-Tawi", Type="Province" },
            new(){ Code ="WSA", LocalName="Western Samar", Name="Western Samar", Type="Province" },
            new(){ Code ="ZMB", LocalName="Zambales", Name="Zambales", Type="Province" },
            new(){ Code ="ZAN", LocalName="Zamboanga del Norte", Name="Zamboanga del Norte", Type="Province" },
            new(){ Code ="ZAS", LocalName="Zamboanga del Sur", Name="Zamboanga del Sur", Type="Province" },
            new(){ Code ="ZSI", LocalName="Zamboanga Sibuguey", Name="Zamboanga Sibuguey", Type="Province" }

        });
    }
}
