using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsSI()
    {
        AddSubdivisions("SI", new List<Subdivision>()
        {
            new(){ Code ="190", LocalName="alec", Name="alec", Type="Municipality" },
            new(){ Code ="33", LocalName="alovci", Name="alovci", Type="Municipality" },
            new(){ Code ="146", LocalName="elezniki", Name="elezniki", Type="Municipality" },
            new(){ Code ="183", LocalName="empeter-Vrtojba", Name="empeter-Vrtojba", Type="Municipality" },
            new(){ Code ="117", LocalName="encur", Name="encur", Type="Municipality" },
            new(){ Code ="118", LocalName="entilj", Name="entilj", Type="Municipality" },
            new(){ Code ="119", LocalName="entjernej", Name="entjernej", Type="Municipality" },
            new(){ Code ="120", LocalName="entjur", Name="entjur", Type="Municipality" },
            new(){ Code ="211", LocalName="entrupert", Name="entrupert", Type="Municipality" },
            new(){ Code ="191", LocalName="etale", Name="etale", Type="Municipality" },
            new(){ Code ="147", LocalName="iri", Name="iri", Type="Municipality" },
            new(){ Code ="192", LocalName="irovnica", Name="irovnica", Type="Municipality" },
            new(){ Code ="121", LocalName="kocjan", Name="kocjan", Type="Municipality" },
            new(){ Code ="122", LocalName="kofja Loka", Name="kofja Loka", Type="Municipality" },
            new(){ Code ="123", LocalName="kofljica", Name="kofljica", Type="Municipality" },
            new(){ Code ="124", LocalName="marje pri Jelah", Name="marje pri Jelah", Type="Municipality" },
            new(){ Code ="206", LocalName="marjeke Toplice", Name="marjeke Toplice", Type="Municipality" },
            new(){ Code ="125", LocalName="martno ob Paki", Name="martno ob Paki", Type="Municipality" },
            new(){ Code ="194", LocalName="martno pri Litiji", Name="martno pri Litiji", Type="Municipality" },
            new(){ Code ="126", LocalName="otanj", Name="otanj", Type="Municipality" },
            new(){ Code ="127", LocalName="tore", Name="tore", Type="Municipality" },
            new(){ Code ="193", LocalName="uemberk", Name="uemberk", Type="Municipality" },
            new(){ Code ="1", LocalName="Ajdovcina", Name="Ajdovcina", Type="Municipality" },
            new(){ Code ="213", LocalName="Ankaran", Name="Ankaran", Type="Municipality" },
            new(){ Code ="195", LocalName="Apace", Name="Apace", Type="Municipality" },
            new(){ Code ="2", LocalName="Beltinci", Name="Beltinci", Type="Municipality" },
            new(){ Code ="148", LocalName="Benedikt", Name="Benedikt", Type="Municipality" },
            new(){ Code ="149", LocalName="Bistrica ob Sotli", Name="Bistrica ob Sotli", Type="Municipality" },
            new(){ Code ="3", LocalName="Bled", Name="Bled", Type="Municipality" },
            new(){ Code ="150", LocalName="Bloke", Name="Bloke", Type="Municipality" },
            new(){ Code ="4", LocalName="Bohinj", Name="Bohinj", Type="Municipality" },
            new(){ Code ="5", LocalName="Borovnica", Name="Borovnica", Type="Municipality" },
            new(){ Code ="6", LocalName="Bovec", Name="Bovec", Type="Municipality" },
            new(){ Code ="151", LocalName="Braslovce", Name="Braslovce", Type="Municipality" },
            new(){ Code ="7", LocalName="Brda", Name="Brda", Type="Municipality" },
            new(){ Code ="9", LocalName="Breice", Name="Breice", Type="Municipality" },
            new(){ Code ="8", LocalName="Brezovica", Name="Brezovica", Type="Municipality" },
            new(){ Code ="152", LocalName="Cankova", Name="Cankova", Type="Municipality" },
            new(){ Code ="11", LocalName="Celje", Name="Celje", Type="Municipality" },
            new(){ Code ="12", LocalName="Cerklje na Gorenjskem", Name="Cerklje na Gorenjskem", Type="Municipality" },
            new(){ Code ="13", LocalName="Cerknica", Name="Cerknica", Type="Municipality" },
            new(){ Code ="14", LocalName="Cerkno", Name="Cerkno", Type="Municipality" },
            new(){ Code ="153", LocalName="Cerkvenjak", Name="Cerkvenjak", Type="Municipality" },
            new(){ Code ="196", LocalName="Cirkulane", Name="Cirkulane", Type="Municipality" },
            new(){ Code ="15", LocalName="Crenovci", Name="Crenovci", Type="Municipality" },
            new(){ Code ="16", LocalName="Crna na Korokem", Name="Crna na Korokem", Type="Municipality" },
            new(){ Code ="17", LocalName="Crnomelj", Name="Crnomelj", Type="Municipality" },
            new(){ Code ="18", LocalName="Destrnik", Name="Destrnik", Type="Municipality" },
            new(){ Code ="19", LocalName="Divaca", Name="Divaca", Type="Municipality" },
            new(){ Code ="154", LocalName="Dobje", Name="Dobje", Type="Municipality" },
            new(){ Code ="20", LocalName="Dobrepolje", Name="Dobrepolje", Type="Municipality" },
            new(){ Code ="155", LocalName="Dobrna", Name="Dobrna", Type="Municipality" },
            new(){ Code ="21", LocalName="Dobrova-Polhov Gradec", Name="Dobrova-Polhov Gradec", Type="Municipality" },
            new(){ Code ="156", LocalName="Dobrovnik", Name="Dobrovnik", Type="Municipality" },
            new(){ Code ="22", LocalName="Dol pri Ljubljani", Name="Dol pri Ljubljani", Type="Municipality" },
            new(){ Code ="157", LocalName="Dolenjske Toplice", Name="Dolenjske Toplice", Type="Municipality" },
            new(){ Code ="23", LocalName="Domale", Name="Domale", Type="Municipality" },
            new(){ Code ="24", LocalName="Dornava", Name="Dornava", Type="Municipality" },
            new(){ Code ="25", LocalName="Dravograd", Name="Dravograd", Type="Municipality" },
            new(){ Code ="26", LocalName="Duplek", Name="Duplek", Type="Municipality" },
            new(){ Code ="27", LocalName="Gorenja vas-Poljane", Name="Gorenja vas-Poljane", Type="Municipality" },
            new(){ Code ="28", LocalName="Gorinica", Name="Gorinica", Type="Municipality" },
            new(){ Code ="207", LocalName="Gorje", Name="Gorje", Type="Municipality" },
            new(){ Code ="29", LocalName="Gornja Radgona", Name="Gornja Radgona", Type="Municipality" },
            new(){ Code ="30", LocalName="Gornji Grad", Name="Gornji Grad", Type="Municipality" },
            new(){ Code ="31", LocalName="Gornji Petrovci", Name="Gornji Petrovci", Type="Municipality" },
            new(){ Code ="158", LocalName="Grad", Name="Grad", Type="Municipality" },
            new(){ Code ="32", LocalName="Grosuplje", Name="Grosuplje", Type="Municipality" },
            new(){ Code ="159", LocalName="Hajdina", Name="Hajdina", Type="Municipality" },
            new(){ Code ="160", LocalName="Hoce-Slivnica", Name="Hoce-Slivnica", Type="Municipality" },
            new(){ Code ="161", LocalName="Hodo", Name="Hodo", Type="Municipality" },
            new(){ Code ="162", LocalName="Horjul", Name="Horjul", Type="Municipality" },
            new(){ Code ="34", LocalName="Hrastnik", Name="Hrastnik", Type="Municipality" },
            new(){ Code ="35", LocalName="Hrpelje-Kozina", Name="Hrpelje-Kozina", Type="Municipality" },
            new(){ Code ="36", LocalName="Idrija", Name="Idrija", Type="Municipality" },
            new(){ Code ="37", LocalName="Ig", Name="Ig", Type="Municipality" },
            new(){ Code ="38", LocalName="Ilirska Bistrica", Name="Ilirska Bistrica", Type="Municipality" },
            new(){ Code ="39", LocalName="Ivancna Gorica", Name="Ivancna Gorica", Type="Municipality" },
            new(){ Code ="40", LocalName="Izola", Name="Izola", Type="Municipality" },
            new(){ Code ="41", LocalName="Jesenice", Name="Jesenice", Type="Municipality" },
            new(){ Code ="163", LocalName="Jezersko", Name="Jezersko", Type="Municipality" },
            new(){ Code ="42", LocalName="Jurinci", Name="Jurinci", Type="Municipality" },
            new(){ Code ="43", LocalName="Kamnik", Name="Kamnik", Type="Municipality" },
            new(){ Code ="44", LocalName="Kanal", Name="Kanal", Type="Municipality" },
            new(){ Code ="45", LocalName="Kidricevo", Name="Kidricevo", Type="Municipality" },
            new(){ Code ="46", LocalName="Kobarid", Name="Kobarid", Type="Municipality" },
            new(){ Code ="47", LocalName="Kobilje", Name="Kobilje", Type="Municipality" },
            new(){ Code ="48", LocalName="Kocevje", Name="Kocevje", Type="Municipality" },
            new(){ Code ="49", LocalName="Komen", Name="Komen", Type="Municipality" },
            new(){ Code ="164", LocalName="Komenda", Name="Komenda", Type="Municipality" },
            new(){ Code ="50", LocalName="Koper", Name="Koper", Type="Municipality" },
            new(){ Code ="197", LocalName="Kosanjevica na Krki", Name="Kosanjevica na Krki", Type="Municipality" },
            new(){ Code ="165", LocalName="Kostel", Name="Kostel", Type="Municipality" },
            new(){ Code ="51", LocalName="Kozje", Name="Kozje", Type="Municipality" },
            new(){ Code ="54", LocalName="Krko", Name="Krko", Type="Municipality" },
            new(){ Code ="52", LocalName="Kranj", Name="Kranj", Type="Municipality" },
            new(){ Code ="53", LocalName="Kranjska Gora", Name="Kranjska Gora", Type="Municipality" },
            new(){ Code ="166", LocalName="Krievci", Name="Krievci", Type="Municipality" },
            new(){ Code ="55", LocalName="Kungota", Name="Kungota", Type="Municipality" },
            new(){ Code ="56", LocalName="Kuzma", Name="Kuzma", Type="Municipality" },
            new(){ Code ="57", LocalName="Lako", Name="Lako", Type="Municipality" },
            new(){ Code ="58", LocalName="Lenart", Name="Lenart", Type="Municipality" },
            new(){ Code ="59", LocalName="Lendava", Name="Lendava", Type="Municipality" },
            new(){ Code ="60", LocalName="Litija", Name="Litija", Type="Municipality" },
            new(){ Code ="61", LocalName="Ljubljana", Name="Ljubljana", Type="Municipality" },
            new(){ Code ="62", LocalName="Ljubno", Name="Ljubno", Type="Municipality" },
            new(){ Code ="63", LocalName="Ljutomer", Name="Ljutomer", Type="Municipality" },
            new(){ Code ="65", LocalName="Loka dolina", Name="Loka dolina", Type="Municipality" },
            new(){ Code ="66", LocalName="Loki Potok", Name="Loki Potok", Type="Municipality" },
            new(){ Code ="64", LocalName="Logatec", Name="Logatec", Type="Municipality" },
            new(){ Code ="208", LocalName="Log-Dragomer", Name="Log-Dragomer", Type="Municipality" },
            new(){ Code ="167", LocalName="Lovrenc na Pohorju", Name="Lovrenc na Pohorju", Type="Municipality" },
            new(){ Code ="67", LocalName="Luce", Name="Luce", Type="Municipality" },
            new(){ Code ="68", LocalName="Lukovica", Name="Lukovica", Type="Municipality" },
            new(){ Code ="69", LocalName="Majperk", Name="Majperk", Type="Municipality" },
            new(){ Code ="198", LocalName="Makole", Name="Makole", Type="Municipality" },
            new(){ Code ="70", LocalName="Maribor", Name="Maribor", Type="Municipality" },
            new(){ Code ="168", LocalName="Markovci", Name="Markovci", Type="Municipality" },
            new(){ Code ="74", LocalName="Meica", Name="Meica", Type="Municipality" },
            new(){ Code ="71", LocalName="Medvode", Name="Medvode", Type="Municipality" },
            new(){ Code ="72", LocalName="Menge", Name="Menge", Type="Municipality" },
            new(){ Code ="73", LocalName="Metlika", Name="Metlika", Type="Municipality" },
            new(){ Code ="169", LocalName="Miklav na Dravskem polju", Name="Miklav na Dravskem polju", Type="Municipality" },
            new(){ Code ="75", LocalName="Miren-Kostanjevica", Name="Miren-Kostanjevica", Type="Municipality" },
            new(){ Code ="212", LocalName="Mirna", Name="Mirna", Type="Municipality" },
            new(){ Code ="170", LocalName="Mirna Pec", Name="Mirna Pec", Type="Municipality" },
            new(){ Code ="76", LocalName="Mislinja", Name="Mislinja", Type="Municipality" },
            new(){ Code ="199", LocalName="Mokronog-Trebelno", Name="Mokronog-Trebelno", Type="Municipality" },
            new(){ Code ="77", LocalName="Moravce", Name="Moravce", Type="Municipality" },
            new(){ Code ="78", LocalName="Moravske Toplice", Name="Moravske Toplice", Type="Municipality" },
            new(){ Code ="79", LocalName="Mozirje", Name="Mozirje", Type="Municipality" },
            new(){ Code ="80", LocalName="Murska Sobota", Name="Murska Sobota", Type="Municipality" },
            new(){ Code ="81", LocalName="Muta", Name="Muta", Type="Municipality" },
            new(){ Code ="82", LocalName="Naklo", Name="Naklo", Type="Municipality" },
            new(){ Code ="83", LocalName="Nazarje", Name="Nazarje", Type="Municipality" },
            new(){ Code ="84", LocalName="Nova Gorica", Name="Nova Gorica", Type="Municipality" },
            new(){ Code ="85", LocalName="Novo mesto", Name="Novo mesto", Type="Municipality" },
            new(){ Code ="86", LocalName="Odranci", Name="Odranci", Type="Municipality" },
            new(){ Code ="171", LocalName="Oplotnica", Name="Oplotnica", Type="Municipality" },
            new(){ Code ="87", LocalName="Ormo", Name="Ormo", Type="Municipality" },
            new(){ Code ="88", LocalName="Osilnica", Name="Osilnica", Type="Municipality" },
            new(){ Code ="89", LocalName="Pesnica", Name="Pesnica", Type="Municipality" },
            new(){ Code ="90", LocalName="Piran", Name="Piran", Type="Municipality" },
            new(){ Code ="91", LocalName="Pivka", Name="Pivka", Type="Municipality" },
            new(){ Code ="92", LocalName="Podcetrtek", Name="Podcetrtek", Type="Municipality" },
            new(){ Code ="172", LocalName="Podlehnik", Name="Podlehnik", Type="Municipality" },
            new(){ Code ="93", LocalName="Podvelka", Name="Podvelka", Type="Municipality" },
            new(){ Code ="200", LocalName="Poljcane", Name="Poljcane", Type="Municipality" },
            new(){ Code ="173", LocalName="Polzela", Name="Polzela", Type="Municipality" },
            new(){ Code ="94", LocalName="Postojna", Name="Postojna", Type="Municipality" },
            new(){ Code ="174", LocalName="Prebold", Name="Prebold", Type="Municipality" },
            new(){ Code ="95", LocalName="Preddvor", Name="Preddvor", Type="Municipality" },
            new(){ Code ="175", LocalName="Prevalje", Name="Prevalje", Type="Municipality" },
            new(){ Code ="96", LocalName="Ptuj", Name="Ptuj", Type="Municipality" },
            new(){ Code ="97", LocalName="Puconci", Name="Puconci", Type="Municipality" },
            new(){ Code ="98", LocalName="Race-Fram", Name="Race-Fram", Type="Municipality" },
            new(){ Code ="99", LocalName="Radece", Name="Radece", Type="Municipality" },
            new(){ Code ="100", LocalName="Radenci", Name="Radenci", Type="Municipality" },
            new(){ Code ="101", LocalName="Radlje ob Dravi", Name="Radlje ob Dravi", Type="Municipality" },
            new(){ Code ="102", LocalName="Radovljica", Name="Radovljica", Type="Municipality" },
            new(){ Code ="103", LocalName="Ravne na Korokem", Name="Ravne na Korokem", Type="Municipality" },
            new(){ Code ="176", LocalName="Razkrije", Name="Razkrije", Type="Municipality" },
            new(){ Code ="209", LocalName="Recica ob Savinji", Name="Recica ob Savinji", Type="Municipality" },
            new(){ Code ="201", LocalName="Renèe-Vogrsko", Name="Renèe-Vogrsko", Type="Municipality" },
            new(){ Code ="104", LocalName="Ribnica", Name="Ribnica", Type="Municipality" },
            new(){ Code ="177", LocalName="Ribnica na Pohorju", Name="Ribnica na Pohorju", Type="Municipality" },
            new(){ Code ="106", LocalName="Rogaka Slatina", Name="Rogaka Slatina", Type="Municipality" },
            new(){ Code ="105", LocalName="Rogaovci", Name="Rogaovci", Type="Municipality" },
            new(){ Code ="107", LocalName="Rogatec", Name="Rogatec", Type="Municipality" },
            new(){ Code ="108", LocalName="Rue", Name="Rue", Type="Municipality" },
            new(){ Code ="111", LocalName="Seana", Name="Seana", Type="Municipality" },
            new(){ Code ="178", LocalName="Selnica ob Dravi", Name="Selnica ob Dravi", Type="Municipality" },
            new(){ Code ="109", LocalName="Semic", Name="Semic", Type="Municipality" },
            new(){ Code ="110", LocalName="Sevnica", Name="Sevnica", Type="Municipality" },
            new(){ Code ="112", LocalName="Slovenj Gradec", Name="Slovenj Gradec", Type="Municipality" },
            new(){ Code ="113", LocalName="Slovenska Bistrica", Name="Slovenska Bistrica", Type="Municipality" },
            new(){ Code ="114", LocalName="Slovenske Konjice", Name="Slovenske Konjice", Type="Municipality" },
            new(){ Code ="179", LocalName="Sodraica", Name="Sodraica", Type="Municipality" },
            new(){ Code ="180", LocalName="Solcava", Name="Solcava", Type="Municipality" },
            new(){ Code ="202", LocalName="Sredice ob Dravi", Name="Sredice ob Dravi", Type="Municipality" },
            new(){ Code ="115", LocalName="Stare", Name="Stare", Type="Municipality" },
            new(){ Code ="203", LocalName="Straa", Name="Straa", Type="Municipality" },
            new(){ Code ="181", LocalName="Sveta Ana", Name="Sveta Ana", Type="Municipality" },
            new(){ Code ="182", LocalName="Sveti Andra v Slovenskih goricah", Name="Sveti Andra v Slovenskih goricah", Type="Municipality" },
            new(){ Code ="116", LocalName="Sveti Jurij", Name="Sveti Jurij", Type="Municipality" },
            new(){ Code ="210", LocalName="Sveti Jurij v Slovenskih Goricah", Name="Sveti Jurij v Slovenskih Goricah", Type="Municipality" },
            new(){ Code ="205", LocalName="Sveti Toma", Name="Sveti Toma", Type="Municipality" },
            new(){ Code ="184", LocalName="Tabor", Name="Tabor", Type="Municipality" },
            new(){ Code ="10", LocalName="Tiina", Name="Tiina", Type="Municipality" },
            new(){ Code ="128", LocalName="Tolmin", Name="Tolmin", Type="Municipality" },
            new(){ Code ="131", LocalName="Tric", Name="Tric", Type="Municipality" },
            new(){ Code ="129", LocalName="Trbovlje", Name="Trbovlje", Type="Municipality" },
            new(){ Code ="130", LocalName="Trebnje", Name="Trebnje", Type="Municipality" },
            new(){ Code ="185", LocalName="Trnovska vas", Name="Trnovska vas", Type="Municipality" },
            new(){ Code ="186", LocalName="Trzin", Name="Trzin", Type="Municipality" },
            new(){ Code ="132", LocalName="Turnice", Name="Turnice", Type="Municipality" },
            new(){ Code ="133", LocalName="Velenje", Name="Velenje", Type="Municipality" },
            new(){ Code ="187", LocalName="Velika Polana", Name="Velika Polana", Type="Municipality" },
            new(){ Code ="134", LocalName="Velike Lace", Name="Velike Lace", Type="Municipality" },
            new(){ Code ="188", LocalName="Verej", Name="Verej", Type="Municipality" },
            new(){ Code ="135", LocalName="Videm", Name="Videm", Type="Municipality" },
            new(){ Code ="136", LocalName="Vipava", Name="Vipava", Type="Municipality" },
            new(){ Code ="137", LocalName="Vitanje", Name="Vitanje", Type="Municipality" },
            new(){ Code ="138", LocalName="Vodice", Name="Vodice", Type="Municipality" },
            new(){ Code ="139", LocalName="Vojnik", Name="Vojnik", Type="Municipality" },
            new(){ Code ="189", LocalName="Vransko", Name="Vransko", Type="Municipality" },
            new(){ Code ="140", LocalName="Vrhnika", Name="Vrhnika", Type="Municipality" },
            new(){ Code ="141", LocalName="Vuzenica", Name="Vuzenica", Type="Municipality" },
            new(){ Code ="142", LocalName="Zagorje ob Savi", Name="Zagorje ob Savi", Type="Municipality" },
            new(){ Code ="143", LocalName="Zavrc", Name="Zavrc", Type="Municipality" },
            new(){ Code ="144", LocalName="Zrece", Name="Zrece", Type="Municipality" }

        });
    }
}
