using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsTR()
    {
        AddSubdivisions("TR", new List<Subdivision>()
        {
            new(){ Code ="1", LocalName="Adana", Name="Adana", Type="Province" },
            new(){ Code ="2", LocalName="Adiyaman", Name="Adiyaman", Type="Province" },
            new(){ Code ="3", LocalName="Afyonkarahisar", Name="Afyonkarahisar", Type="Province" },
            new(){ Code ="4", LocalName="Agri", Name="Agri", Type="Province" },
            new(){ Code ="68", LocalName="Aksaray", Name="Aksaray", Type="Province" },
            new(){ Code ="5", LocalName="Amasya", Name="Amasya", Type="Province" },
            new(){ Code ="6", LocalName="Ankara", Name="Ankara", Type="Province" },
            new(){ Code ="7", LocalName="Antalya", Name="Antalya", Type="Province" },
            new(){ Code ="75", LocalName="Ardahan", Name="Ardahan", Type="Province" },
            new(){ Code ="8", LocalName="Artvin", Name="Artvin", Type="Province" },
            new(){ Code ="9", LocalName="Aydin", Name="Aydin", Type="Province" },
            new(){ Code ="10", LocalName="Balikesir", Name="Balikesir", Type="Province" },
            new(){ Code ="74", LocalName="Bartin", Name="Bartin", Type="Province" },
            new(){ Code ="72", LocalName="Batman", Name="Batman", Type="Province" },
            new(){ Code ="69", LocalName="Bayburt", Name="Bayburt", Type="Province" },
            new(){ Code ="11", LocalName="Bilecik", Name="Bilecik", Type="Province" },
            new(){ Code ="12", LocalName="Bingöl", Name="Bingöl", Type="Province" },
            new(){ Code ="13", LocalName="Bitlis", Name="Bitlis", Type="Province" },
            new(){ Code ="14", LocalName="Bolu", Name="Bolu", Type="Province" },
            new(){ Code ="15", LocalName="Burdur", Name="Burdur", Type="Province" },
            new(){ Code ="16", LocalName="Bursa", Name="Bursa", Type="Province" },
            new(){ Code ="17", LocalName="Canakkale", Name="Canakkale", Type="Province" },
            new(){ Code ="18", LocalName="Çankiri", Name="Çankiri", Type="Province" },
            new(){ Code ="19", LocalName="Corum", Name="Corum", Type="Province" },
            new(){ Code ="20", LocalName="Denizli", Name="Denizli", Type="Province" },
            new(){ Code ="21", LocalName="Diyarbakir", Name="Diyarbakir", Type="Province" },
            new(){ Code ="81", LocalName="Düzce", Name="Düzce", Type="Province" },
            new(){ Code ="22", LocalName="Edirne", Name="Edirne", Type="Province" },
            new(){ Code ="23", LocalName="Elazig", Name="Elazig", Type="Province" },
            new(){ Code ="24", LocalName="Erzincan", Name="Erzincan", Type="Province" },
            new(){ Code ="25", LocalName="Erzurum", Name="Erzurum", Type="Province" },
            new(){ Code ="26", LocalName="Eskisehir", Name="Eskisehir", Type="Province" },
            new(){ Code ="27", LocalName="Gaziantep", Name="Gaziantep", Type="Province" },
            new(){ Code ="28", LocalName="Giresun", Name="Giresun", Type="Province" },
            new(){ Code ="29", LocalName="Gümüshane", Name="Gümüshane", Type="Province" },
            new(){ Code ="30", LocalName="Hakkari", Name="Hakkari", Type="Province" },
            new(){ Code ="31", LocalName="Hatay", Name="Hatay", Type="Province" },
            new(){ Code ="76", LocalName="Igdir", Name="Igdir", Type="Province" },
            new(){ Code ="32", LocalName="Isparta", Name="Isparta", Type="Province" },
            new(){ Code ="34", LocalName="Istanbul", Name="Istanbul", Type="Province" },
            new(){ Code ="35", LocalName="Izmir", Name="Izmir", Type="Province" },
            new(){ Code ="46", LocalName="Kahramanmaras", Name="Kahramanmaras", Type="Province" },
            new(){ Code ="78", LocalName="Karabuk", Name="Karabuk", Type="Province" },
            new(){ Code ="70", LocalName="Karaman", Name="Karaman", Type="Province" },
            new(){ Code ="36", LocalName="Kars", Name="Kars", Type="Province" },
            new(){ Code ="37", LocalName="Kastamonu", Name="Kastamonu", Type="Province" },
            new(){ Code ="38", LocalName="Kayseri", Name="Kayseri", Type="Province" },
            new(){ Code ="79", LocalName="Kilis", Name="Kilis", Type="Province" },
            new(){ Code ="71", LocalName="Kirikkale", Name="Kirikkale", Type="Province" },
            new(){ Code ="39", LocalName="Kirklareli", Name="Kirklareli", Type="Province" },
            new(){ Code ="40", LocalName="Kirsehir", Name="Kirsehir", Type="Province" },
            new(){ Code ="41", LocalName="Kocaeli", Name="Kocaeli", Type="Province" },
            new(){ Code ="42", LocalName="Konya", Name="Konya", Type="Province" },
            new(){ Code ="43", LocalName="Kütahya", Name="Kütahya", Type="Province" },
            new(){ Code ="44", LocalName="Malatya", Name="Malatya", Type="Province" },
            new(){ Code ="45", LocalName="Manisa", Name="Manisa", Type="Province" },
            new(){ Code ="47", LocalName="Mardin", Name="Mardin", Type="Province" },
            new(){ Code ="33", LocalName="Mersin", Name="Mersin", Type="Province" },
            new(){ Code ="48", LocalName="Mugla", Name="Mugla", Type="Province" },
            new(){ Code ="49", LocalName="Mus", Name="Mus", Type="Province" },
            new(){ Code ="50", LocalName="Nevsehir", Name="Nevsehir", Type="Province" },
            new(){ Code ="51", LocalName="Nigde", Name="Nigde", Type="Province" },
            new(){ Code ="52", LocalName="Ordu", Name="Ordu", Type="Province" },
            new(){ Code ="80", LocalName="Osmaniye", Name="Osmaniye", Type="Province" },
            new(){ Code ="53", LocalName="Rize", Name="Rize", Type="Province" },
            new(){ Code ="54", LocalName="Sakarya", Name="Sakarya", Type="Province" },
            new(){ Code ="55", LocalName="Samsun", Name="Samsun", Type="Province" },
            new(){ Code ="63", LocalName="Sanliurfa", Name="Sanliurfa", Type="Province" },
            new(){ Code ="56", LocalName="Siirt", Name="Siirt", Type="Province" },
            new(){ Code ="57", LocalName="Sinop", Name="Sinop", Type="Province" },
            new(){ Code ="73", LocalName="Sirnak", Name="Sirnak", Type="Province" },
            new(){ Code ="58", LocalName="Sivas", Name="Sivas", Type="Province" },
            new(){ Code ="59", LocalName="Tekirdag", Name="Tekirdag", Type="Province" },
            new(){ Code ="60", LocalName="Tokat", Name="Tokat", Type="Province" },
            new(){ Code ="61", LocalName="Trabzon", Name="Trabzon", Type="Province" },
            new(){ Code ="62", LocalName="Tunceli", Name="Tunceli", Type="Province" },
            new(){ Code ="64", LocalName="Usak", Name="Usak", Type="Province" },
            new(){ Code ="65", LocalName="Van", Name="Van", Type="Province" },
            new(){ Code ="77", LocalName="Yalova", Name="Yalova", Type="Province" },
            new(){ Code ="66", LocalName="Yozgat", Name="Yozgat", Type="Province" },
            new(){ Code ="67", LocalName="Zonguldak", Name="Zonguldak", Type="Province" }

        });
    }
}
