using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsUG()
    {
        AddSubdivisions("UG", new List<Subdivision>()
        {
            new(){ Code ="314", LocalName="Abim", Name="Abim", Type="District" },
            new(){ Code ="301", LocalName="Adjumani", Name="Adjumani", Type="District" },
            new(){ Code ="315", LocalName="Amolatar", Name="Amolatar", Type="District" },
            new(){ Code ="216", LocalName="Amuria", Name="Amuria", Type="District" },
            new(){ Code ="316", LocalName="Amuru", Name="Amuru", Type="District" },
            new(){ Code ="302", LocalName="Apac", Name="Apac", Type="District" },
            new(){ Code ="303", LocalName="Arua", Name="Arua", Type="District" },
            new(){ Code ="217", LocalName="Budaka", Name="Budaka", Type="District" },
            new(){ Code ="218", LocalName="Bududa", Name="Bududa", Type="District" },
            new(){ Code ="201", LocalName="Bugiri", Name="Bugiri", Type="District" },
            new(){ Code ="420", LocalName="Buhweju", Name="Buhweju", Type="District" },
            new(){ Code ="117", LocalName="Buikwe", Name="Buikwe", Type="District" },
            new(){ Code ="219", LocalName="Bukedea", Name="Bukedea", Type="District" },
            new(){ Code ="118", LocalName="Bukomansibi", Name="Bukomansibi", Type="District" },
            new(){ Code ="220", LocalName="Bukwa", Name="Bukwa", Type="District" },
            new(){ Code ="225", LocalName="Bulambuli", Name="Bulambuli", Type="District" },
            new(){ Code ="416", LocalName="Buliisa", Name="Buliisa", Type="District" },
            new(){ Code ="401", LocalName="Bundibugyo", Name="Bundibugyo", Type="District" },
            new(){ Code ="402", LocalName="Bushenyi", Name="Bushenyi", Type="District" },
            new(){ Code ="202", LocalName="Busia", Name="Busia", Type="District" },
            new(){ Code ="221", LocalName="Butaleja", Name="Butaleja", Type="District" },
            new(){ Code ="119", LocalName="Butambala", Name="Butambala", Type="District" },
            new(){ Code ="120", LocalName="Buvuma", Name="Buvuma", Type="District" },
            new(){ Code ="226", LocalName="Buyende", Name="Buyende", Type="District" },
            new(){ Code ="317", LocalName="Dokolo", Name="Dokolo", Type="District" },
            new(){ Code ="121", LocalName="Gomba", Name="Gomba", Type="District" },
            new(){ Code ="304", LocalName="Gulu", Name="Gulu", Type="District" },
            new(){ Code ="403", LocalName="Hoima", Name="Hoima", Type="District" },
            new(){ Code ="417", LocalName="Ibanda", Name="Ibanda", Type="District" },
            new(){ Code ="203", LocalName="Iganga", Name="Iganga", Type="District" },
            new(){ Code ="418", LocalName="Isingiro", Name="Isingiro", Type="District" },
            new(){ Code ="204", LocalName="Jinja", Name="Jinja", Type="District" },
            new(){ Code ="318", LocalName="Kaabong", Name="Kaabong", Type="District" },
            new(){ Code ="404", LocalName="Kabale", Name="Kabale", Type="District" },
            new(){ Code ="405", LocalName="Kabarole", Name="Kabarole", Type="District" },
            new(){ Code ="213", LocalName="Kaberamaido", Name="Kaberamaido", Type="District" },
            new(){ Code ="101", LocalName="Kalangala", Name="Kalangala", Type="District" },
            new(){ Code ="222", LocalName="Kaliro", Name="Kaliro", Type="District" },
            new(){ Code ="122", LocalName="Kalungu", Name="Kalungu", Type="District" },
            new(){ Code ="102", LocalName="Kampala", Name="Kampala", Type="City" },
            new(){ Code ="205", LocalName="Kamuli", Name="Kamuli", Type="District" },
            new(){ Code ="413", LocalName="Kamwenge", Name="Kamwenge", Type="District" },
            new(){ Code ="414", LocalName="Kanungu", Name="Kanungu", Type="District" },
            new(){ Code ="206", LocalName="Kapchorwa", Name="Kapchorwa", Type="District" },
            new(){ Code ="406", LocalName="Kasese", Name="Kasese", Type="District" },
            new(){ Code ="207", LocalName="Katakwi", Name="Katakwi", Type="District" },
            new(){ Code ="112", LocalName="Kayunga", Name="Kayunga", Type="District" },
            new(){ Code ="407", LocalName="Kibaale", Name="Kibaale", Type="District" },
            new(){ Code ="103", LocalName="Kiboga", Name="Kiboga", Type="District" },
            new(){ Code ="227", LocalName="Kibuku", Name="Kibuku", Type="District" },
            new(){ Code ="419", LocalName="Kiruhura", Name="Kiruhura", Type="District" },
            new(){ Code ="421", LocalName="Kiryandongo", Name="Kiryandongo", Type="District" },
            new(){ Code ="408", LocalName="Kisoro", Name="Kisoro", Type="District" },
            new(){ Code ="305", LocalName="Kitgum", Name="Kitgum", Type="District" },
            new(){ Code ="319", LocalName="Koboko", Name="Koboko", Type="District" },
            new(){ Code ="325", LocalName="Kole", Name="Kole", Type="District" },
            new(){ Code ="306", LocalName="Kotido", Name="Kotido", Type="District" },
            new(){ Code ="208", LocalName="Kumi", Name="Kumi", Type="District" },
            new(){ Code ="228", LocalName="Kween", Name="Kween", Type="District" },
            new(){ Code ="123", LocalName="Kyankwanzi", Name="Kyankwanzi", Type="District" },
            new(){ Code ="422", LocalName="Kyegegwa", Name="Kyegegwa", Type="District" },
            new(){ Code ="415", LocalName="Kyenjojo", Name="Kyenjojo", Type="District" },
            new(){ Code ="326", LocalName="Lamwo", Name="Lamwo", Type="District" },
            new(){ Code ="307", LocalName="Lira", Name="Lira", Type="District" },
            new(){ Code ="229", LocalName="Luuka", Name="Luuka", Type="District" },
            new(){ Code ="104", LocalName="Luwero", Name="Luwero", Type="District" },
            new(){ Code ="124", LocalName="Lwengo", Name="Lwengo", Type="District" },
            new(){ Code ="114", LocalName="Lyantonde", Name="Lyantonde", Type="District" },
            new(){ Code ="223", LocalName="Manafwa", Name="Manafwa", Type="District" },
            new(){ Code ="320", LocalName="Maracha", Name="Maracha", Type="District" },
            new(){ Code ="105", LocalName="Masaka", Name="Masaka", Type="District" },
            new(){ Code ="409", LocalName="Masindi", Name="Masindi", Type="District" },
            new(){ Code ="244", LocalName="Mayuge", Name="Mayuge", Type="District" },
            new(){ Code ="209", LocalName="Mbale", Name="Mbale", Type="District" },
            new(){ Code ="410", LocalName="Mbarara", Name="Mbarara", Type="District" },
            new(){ Code ="423", LocalName="Mitooma", Name="Mitooma", Type="District" },
            new(){ Code ="115", LocalName="Mityana", Name="Mityana", Type="District" },
            new(){ Code ="308", LocalName="Moroto", Name="Moroto", Type="District" },
            new(){ Code ="309", LocalName="Moyo", Name="Moyo", Type="District" },
            new(){ Code ="106", LocalName="Mpigi", Name="Mpigi", Type="District" },
            new(){ Code ="107", LocalName="Mubende", Name="Mubende", Type="District" },
            new(){ Code ="108", LocalName="Mukono", Name="Mukono", Type="District" },
            new(){ Code ="311", LocalName="Nakapiripirit", Name="Nakapiripirit", Type="District" },
            new(){ Code ="116", LocalName="Nakaseke", Name="Nakaseke", Type="District" },
            new(){ Code ="109", LocalName="Nakasongola", Name="Nakasongola", Type="District" },
            new(){ Code ="230", LocalName="Namayingo", Name="Namayingo", Type="District" },
            new(){ Code ="224", LocalName="Namutumba", Name="Namutumba", Type="District" },
            new(){ Code ="327", LocalName="Napak", Name="Napak", Type="District" },
            new(){ Code ="310", LocalName="Nebbi", Name="Nebbi", Type="District" },
            new(){ Code ="231", LocalName="Ngora", Name="Ngora", Type="District" },
            new(){ Code ="424", LocalName="Ntoroko", Name="Ntoroko", Type="District" },
            new(){ Code ="411", LocalName="Ntungamo", Name="Ntungamo", Type="District" },
            new(){ Code ="328", LocalName="Nwoya", Name="Nwoya", Type="District" },
            new(){ Code ="329", LocalName="Otuke", Name="Otuke", Type="District" },
            new(){ Code ="321", LocalName="Oyam", Name="Oyam", Type="District" },
            new(){ Code ="312", LocalName="Pader", Name="Pader", Type="District" },
            new(){ Code ="210", LocalName="Pallisa", Name="Pallisa", Type="District" },
            new(){ Code ="110", LocalName="Rakai", Name="Rakai", Type="District" },
            new(){ Code ="425", LocalName="Rubirizi", Name="Rubirizi", Type="District" },
            new(){ Code ="412", LocalName="Rukungiri", Name="Rukungiri", Type="District" },
            new(){ Code ="111", LocalName="Sembabule", Name="Sembabule", Type="District" },
            new(){ Code ="232", LocalName="Serere", Name="Serere", Type="District" },
            new(){ Code ="426", LocalName="Sheema", Name="Sheema", Type="District" },
            new(){ Code ="215", LocalName="Sironko", Name="Sironko", Type="District" },
            new(){ Code ="211", LocalName="Soroti", Name="Soroti", Type="District" },
            new(){ Code ="212", LocalName="Tororo", Name="Tororo", Type="District" },
            new(){ Code ="113", LocalName="Wakiso", Name="Wakiso", Type="District" },
            new(){ Code ="313", LocalName="Yumbe", Name="Yumbe", Type="District" },
            new(){ Code ="330", LocalName="Zombo", Name="Zombo", Type="District" }

        });
    }
}
