using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsIT()
    {
        AddSubdivisions("IT", new List<Subdivision>()
        {
            new(){ Code ="AG", LocalName="Agrigento", Name="Agrigento", Type="Province" },
            new(){ Code ="AL", LocalName="Alessandria", Name="Alessandria", Type="Province" },
            new(){ Code ="AN", LocalName="Ancona", Name="Ancona", Type="Province" },
            new(){ Code ="AO", LocalName="Aosta / Aoste", Name="Aosta / Aoste", Type="Province" },
            new(){ Code ="AR", LocalName="Arezzo", Name="Arezzo", Type="Province" },
            new(){ Code ="AP", LocalName="Ascoli Piceno", Name="Ascoli Piceno", Type="Province" },
            new(){ Code ="AT", LocalName="Asti", Name="Asti", Type="Province" },
            new(){ Code ="AV", LocalName="Avellino", Name="Avellino", Type="Province" },
            new(){ Code ="BA", LocalName="Bari", Name="Bari", Type="Province" },
            new(){ Code ="BT", LocalName="Barletta-Andria-Trani", Name="Barletta-Andria-Trani", Type="Province" },
            new(){ Code ="BL", LocalName="Belluno", Name="Belluno", Type="Province" },
            new(){ Code ="BN", LocalName="Benevento", Name="Benevento", Type="Province" },
            new(){ Code ="BG", LocalName="Bergamo", Name="Bergamo", Type="Province" },
            new(){ Code ="BI", LocalName="Biella", Name="Biella", Type="Province" },
            new(){ Code ="BO", LocalName="Bologna", Name="Bologna", Type="Province" },
            new(){ Code ="BZ", LocalName="Bolzano / Bozen", Name="Bolzano / Bozen", Type="Province" },
            new(){ Code ="BS", LocalName="Brescia", Name="Brescia", Type="Province" },
            new(){ Code ="BR", LocalName="Brindisi", Name="Brindisi", Type="Province" },
            new(){ Code ="CA", LocalName="Cagliari", Name="Cagliari", Type="Province" },
            new(){ Code ="CL", LocalName="Caltanissetta", Name="Caltanissetta", Type="Province" },
            new(){ Code ="CB", LocalName="Campobasso", Name="Campobasso", Type="Province" },
            new(){ Code ="CI", LocalName="Carbonia-Iglesias", Name="Carbonia-Iglesias", Type="Province" },
            new(){ Code ="CE", LocalName="Caserta", Name="Caserta", Type="Province" },
            new(){ Code ="CT", LocalName="Catania", Name="Catania", Type="Province" },
            new(){ Code ="CZ", LocalName="Catanzaro", Name="Catanzaro", Type="Province" },
            new(){ Code ="CH", LocalName="Chieti", Name="Chieti", Type="Province" },
            new(){ Code ="CO", LocalName="Como", Name="Como", Type="Province" },
            new(){ Code ="CS", LocalName="Cosenza", Name="Cosenza", Type="Province" },
            new(){ Code ="CR", LocalName="Cremona", Name="Cremona", Type="Province" },
            new(){ Code ="KR", LocalName="Crotone", Name="Crotone", Type="Province" },
            new(){ Code ="CN", LocalName="Cuneo", Name="Cuneo", Type="Province" },
            new(){ Code ="EN", LocalName="Enna", Name="Enna", Type="Province" },
            new(){ Code ="FM", LocalName="Fermo", Name="Fermo", Type="Province" },
            new(){ Code ="FE", LocalName="Ferrara", Name="Ferrara", Type="Province" },
            new(){ Code ="FI", LocalName="Firenze", Name="Firenze", Type="Province" },
            new(){ Code ="FG", LocalName="Foggia", Name="Foggia", Type="Province" },
            new(){ Code ="FC", LocalName="Forlì-Cesena", Name="Forlì-Cesena", Type="Province" },
            new(){ Code ="FR", LocalName="Frosinone", Name="Frosinone", Type="Province" },
            new(){ Code ="GE", LocalName="Genova", Name="Genova", Type="Province" },
            new(){ Code ="GO", LocalName="Gorizia", Name="Gorizia", Type="Province" },
            new(){ Code ="GR", LocalName="Grosseto", Name="Grosseto", Type="Province" },
            new(){ Code ="IM", LocalName="Imperia", Name="Imperia", Type="Province" },
            new(){ Code ="IS", LocalName="Isernia", Name="Isernia", Type="Province" },
            new(){ Code ="SP", LocalName="La Spezia", Name="La Spezia", Type="Province" },
            new(){ Code ="AQ", LocalName="L'Aquila", Name="L'Aquila", Type="Province" },
            new(){ Code ="LT", LocalName="Latina", Name="Latina", Type="Province" },
            new(){ Code ="LE", LocalName="Lecce", Name="Lecce", Type="Province" },
            new(){ Code ="LC", LocalName="Lecco", Name="Lecco", Type="Province" },
            new(){ Code ="LI", LocalName="Livorno", Name="Livorno", Type="Province" },
            new(){ Code ="LO", LocalName="Lodi", Name="Lodi", Type="Province" },
            new(){ Code ="LU", LocalName="Lucca", Name="Lucca", Type="Province" },
            new(){ Code ="MC", LocalName="Macerata", Name="Macerata", Type="Province" },
            new(){ Code ="MN", LocalName="Mantova", Name="Mantova", Type="Province" },
            new(){ Code ="MS", LocalName="Massa-Carrara", Name="Massa-Carrara", Type="Province" },
            new(){ Code ="MT", LocalName="Matera", Name="Matera", Type="Province" },
            new(){ Code ="VS", LocalName="Medio Campidano", Name="Medio Campidano", Type="Province" },
            new(){ Code ="ME", LocalName="Messina", Name="Messina", Type="Province" },
            new(){ Code ="MI", LocalName="Milano", Name="Milano", Type="Province" },
            new(){ Code ="MO", LocalName="Modena", Name="Modena", Type="Province" },
            new(){ Code ="MB", LocalName="Monza e Brianza", Name="Monza e Brianza", Type="Province" },
            new(){ Code ="NA", LocalName="Napoli", Name="Napoli", Type="Province" },
            new(){ Code ="NO", LocalName="Novara", Name="Novara", Type="Province" },
            new(){ Code ="NU", LocalName="Nuoro", Name="Nuoro", Type="Province" },
            new(){ Code ="OG", LocalName="Ogliastra", Name="Ogliastra", Type="Province" },
            new(){ Code ="OT", LocalName="Olbia-Tempio", Name="Olbia-Tempio", Type="Province" },
            new(){ Code ="OR", LocalName="Oristano", Name="Oristano", Type="Province" },
            new(){ Code ="PD", LocalName="Padova", Name="Padova", Type="Province" },
            new(){ Code ="PA", LocalName="Palermo", Name="Palermo", Type="Province" },
            new(){ Code ="PR", LocalName="Parma", Name="Parma", Type="Province" },
            new(){ Code ="PV", LocalName="Pavia", Name="Pavia", Type="Province" },
            new(){ Code ="PG", LocalName="Perugia", Name="Perugia", Type="Province" },
            new(){ Code ="PU", LocalName="Pesaro e Urbino", Name="Pesaro e Urbino", Type="Province" },
            new(){ Code ="PE", LocalName="Pescara", Name="Pescara", Type="Province" },
            new(){ Code ="PC", LocalName="Piacenza", Name="Piacenza", Type="Province" },
            new(){ Code ="PI", LocalName="Pisa", Name="Pisa", Type="Province" },
            new(){ Code ="PT", LocalName="Pistoia", Name="Pistoia", Type="Province" },
            new(){ Code ="PN", LocalName="Pordenone", Name="Pordenone", Type="Province" },
            new(){ Code ="PZ", LocalName="Potenza", Name="Potenza", Type="Province" },
            new(){ Code ="PO", LocalName="Prato", Name="Prato", Type="Province" },
            new(){ Code ="RG", LocalName="Ragusa", Name="Ragusa", Type="Province" },
            new(){ Code ="RA", LocalName="Ravenna", Name="Ravenna", Type="Province" },
            new(){ Code ="RC", LocalName="Reggio Calabria", Name="Reggio Calabria", Type="Province" },
            new(){ Code ="RE", LocalName="Reggio Emilia", Name="Reggio Emilia", Type="Province" },
            new(){ Code ="RI", LocalName="Rieti", Name="Rieti", Type="Province" },
            new(){ Code ="RN", LocalName="Rimini", Name="Rimini", Type="Province" },
            new(){ Code ="RM", LocalName="Roma", Name="Roma", Type="Province" },
            new(){ Code ="RO", LocalName="Rovigo", Name="Rovigo", Type="Province" },
            new(){ Code ="SA", LocalName="Salerno", Name="Salerno", Type="Province" },
            new(){ Code ="SS", LocalName="Sassari", Name="Sassari", Type="Province" },
            new(){ Code ="SV", LocalName="Savona", Name="Savona", Type="Province" },
            new(){ Code ="SI", LocalName="Siena", Name="Siena", Type="Province" },
            new(){ Code ="SR", LocalName="Siracusa", Name="Siracusa", Type="Province" },
            new(){ Code ="SO", LocalName="Sondrio", Name="Sondrio", Type="Province" },
            new(){ Code ="TA", LocalName="Taranto", Name="Taranto", Type="Province" },
            new(){ Code ="TE", LocalName="Teramo", Name="Teramo", Type="Province" },
            new(){ Code ="TR", LocalName="Terni", Name="Terni", Type="Province" },
            new(){ Code ="TO", LocalName="Torino", Name="Torino", Type="Province" },
            new(){ Code ="TP", LocalName="Trapani", Name="Trapani", Type="Province" },
            new(){ Code ="TN", LocalName="Trento", Name="Trento", Type="Province" },
            new(){ Code ="TV", LocalName="Treviso", Name="Treviso", Type="Province" },
            new(){ Code ="TS", LocalName="Trieste", Name="Trieste", Type="Province" },
            new(){ Code ="UD", LocalName="Udine", Name="Udine", Type="Province" },
            new(){ Code ="VA", LocalName="Varese", Name="Varese", Type="Province" },
            new(){ Code ="VE", LocalName="Venezia", Name="Venezia", Type="Province" },
            new(){ Code ="VB", LocalName="Verbano-Cusio-Ossola", Name="Verbano-Cusio-Ossola", Type="Province" },
            new(){ Code ="VC", LocalName="Vercelli", Name="Vercelli", Type="Province" },
            new(){ Code ="VR", LocalName="Verona", Name="Verona", Type="Province" },
            new(){ Code ="VV", LocalName="Vibo Valentia", Name="Vibo Valentia", Type="Province" },
            new(){ Code ="VI", LocalName="Vicenza", Name="Vicenza", Type="Province" },
            new(){ Code ="VT", LocalName="Viterbo", Name="Viterbo", Type="Province" }

        });
    }
}
