using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsLV()
    {
        AddSubdivisions("LV", new List<Subdivision>()
        {
            new(){ Code ="11", LocalName="Adau novads", Name="Adau novads", Type="Municipality" },
            new(){ Code ="1", LocalName="Aglonas novads", Name="Aglonas novads", Type="Municipality" },
            new(){ Code ="2", LocalName="Aizkraukles novads", Name="Aizkraukles novads", Type="Municipality" },
            new(){ Code ="3", LocalName="Aizputes novads", Name="Aizputes novads", Type="Municipality" },
            new(){ Code ="4", LocalName="Aknistes novads", Name="Aknistes novads", Type="Municipality" },
            new(){ Code ="5", LocalName="Alojas novads", Name="Alojas novads", Type="Municipality" },
            new(){ Code ="6", LocalName="Alsungas novads", Name="Alsungas novads", Type="Municipality" },
            new(){ Code ="7", LocalName="Aluksnes novads", Name="Aluksnes novads", Type="Municipality" },
            new(){ Code ="8", LocalName="Amatas novads", Name="Amatas novads", Type="Municipality" },
            new(){ Code ="9", LocalName="Apes novads", Name="Apes novads", Type="Municipality" },
            new(){ Code ="10", LocalName="Auces novads", Name="Auces novads", Type="Municipality" },
            new(){ Code ="12", LocalName="Babites novads", Name="Babites novads", Type="Municipality" },
            new(){ Code ="13", LocalName="Baldones novads", Name="Baldones novads", Type="Municipality" },
            new(){ Code ="14", LocalName="Baltinavas novads", Name="Baltinavas novads", Type="Municipality" },
            new(){ Code ="15", LocalName="Balvu novads", Name="Balvu novads", Type="Municipality" },
            new(){ Code ="16", LocalName="Bauskas novads", Name="Bauskas novads", Type="Municipality" },
            new(){ Code ="17", LocalName="Beverinas novads", Name="Beverinas novads", Type="Municipality" },
            new(){ Code ="18", LocalName="Brocenu novads", Name="Brocenu novads", Type="Municipality" },
            new(){ Code ="19", LocalName="Burtnieku novads", Name="Burtnieku novads", Type="Municipality" },
            new(){ Code ="20", LocalName="Carnikavas novads", Name="Carnikavas novads", Type="Municipality" },
            new(){ Code ="22", LocalName="Cesu novads", Name="Cesu novads", Type="Municipality" },
            new(){ Code ="21", LocalName="Cesvaines novads", Name="Cesvaines novads", Type="Municipality" },
            new(){ Code ="23", LocalName="Ciblas novads", Name="Ciblas novads", Type="Municipality" },
            new(){ Code ="24", LocalName="Dagdas novads", Name="Dagdas novads", Type="Municipality" },
            new(){ Code ="25", LocalName="Daugavpils novads", Name="Daugavpils novads", Type="Municipality" },
            new(){ Code ="26", LocalName="Dobeles novads", Name="Dobeles novads", Type="Municipality" },
            new(){ Code ="27", LocalName="Dundagas novads", Name="Dundagas novads", Type="Municipality" },
            new(){ Code ="28", LocalName="Durbes novads", Name="Durbes novads", Type="Municipality" },
            new(){ Code ="29", LocalName="Engures novads", Name="Engures novads", Type="Municipality" },
            new(){ Code ="30", LocalName="Erglu novads", Name="Erglu novads", Type="Municipality" },
            new(){ Code ="31", LocalName="Garkalnes novads", Name="Garkalnes novads", Type="Municipality" },
            new(){ Code ="32", LocalName="Grobinas novads", Name="Grobinas novads", Type="Municipality" },
            new(){ Code ="33", LocalName="Gulbenes novads", Name="Gulbenes novads", Type="Municipality" },
            new(){ Code ="34", LocalName="Iecavas novads", Name="Iecavas novads", Type="Municipality" },
            new(){ Code ="35", LocalName="Ikkiles novads", Name="Ikkiles novads", Type="Municipality" },
            new(){ Code ="36", LocalName="Ilukstes novads", Name="Ilukstes novads", Type="Municipality" },
            new(){ Code ="37", LocalName="Incukalna novads", Name="Incukalna novads", Type="Municipality" },
            new(){ Code ="40", LocalName="Jaunpils novads", Name="Jaunpils novads", Type="Municipality" },
            new(){ Code ="42", LocalName="Jekabpils novads", Name="Jekabpils novads", Type="Municipality" },
            new(){ Code ="41", LocalName="Jelgavas novads", Name="Jelgavas novads", Type="Municipality" },
            new(){ Code ="43", LocalName="Kandavas novads", Name="Kandavas novads", Type="Municipality" },
            new(){ Code ="44", LocalName="Karsavas novads", Name="Karsavas novads", Type="Municipality" },
            new(){ Code ="51", LocalName="Keguma novads", Name="Keguma novads", Type="Municipality" },
            new(){ Code ="52", LocalName="Kekavas novads", Name="Kekavas novads", Type="Municipality" },
            new(){ Code ="45", LocalName="Kocenu novads", Name="Kocenu novads", Type="Municipality" },
            new(){ Code ="46", LocalName="Kokneses novads", Name="Kokneses novads", Type="Municipality" },
            new(){ Code ="47", LocalName="Kraslavas novads", Name="Kraslavas novads", Type="Municipality" },
            new(){ Code ="48", LocalName="Krimuldas novads", Name="Krimuldas novads", Type="Municipality" },
            new(){ Code ="49", LocalName="Krustpils novads", Name="Krustpils novads", Type="Municipality" },
            new(){ Code ="50", LocalName="Kuldigas novads", Name="Kuldigas novads", Type="Municipality" },
            new(){ Code ="53", LocalName="Lielvardes novads", Name="Lielvardes novads", Type="Municipality" },
            new(){ Code ="55", LocalName="Ligatnes novads", Name="Ligatnes novads", Type="Municipality" },
            new(){ Code ="54", LocalName="Limbau novads", Name="Limbau novads", Type="Municipality" },
            new(){ Code ="56", LocalName="Livanu novads", Name="Livanu novads", Type="Municipality" },
            new(){ Code ="57", LocalName="Lubanas novads", Name="Lubanas novads", Type="Municipality" },
            new(){ Code ="58", LocalName="Ludzas novads", Name="Ludzas novads", Type="Municipality" },
            new(){ Code ="59", LocalName="Madonas novads", Name="Madonas novads", Type="Municipality" },
            new(){ Code ="61", LocalName="Malpils novads", Name="Malpils novads", Type="Municipality" },
            new(){ Code ="62", LocalName="Marupes novads", Name="Marupes novads", Type="Municipality" },
            new(){ Code ="60", LocalName="Mazsalacas novads", Name="Mazsalacas novads", Type="Municipality" },
            new(){ Code ="63", LocalName="Mersraga novads", Name="Mersraga novads", Type="Municipality" },
            new(){ Code ="64", LocalName="Naukenu novads", Name="Naukenu novads", Type="Municipality" },
            new(){ Code ="65", LocalName="Neretas novads", Name="Neretas novads", Type="Municipality" },
            new(){ Code ="66", LocalName="Nicas novads", Name="Nicas novads", Type="Municipality" },
            new(){ Code ="67", LocalName="Ogres novads", Name="Ogres novads", Type="Municipality" },
            new(){ Code ="68", LocalName="Olaines novads", Name="Olaines novads", Type="Municipality" },
            new(){ Code ="69", LocalName="Ozolnieku novads", Name="Ozolnieku novads", Type="Municipality" },
            new(){ Code ="70", LocalName="Pargaujas novads", Name="Pargaujas novads", Type="Municipality" },
            new(){ Code ="71", LocalName="Pavilostas novads", Name="Pavilostas novads", Type="Municipality" },
            new(){ Code ="72", LocalName="Plavinu novads", Name="Plavinu novads", Type="Municipality" },
            new(){ Code ="73", LocalName="Preilu novads", Name="Preilu novads", Type="Municipality" },
            new(){ Code ="74", LocalName="Priekules novads", Name="Priekules novads", Type="Municipality" },
            new(){ Code ="75", LocalName="Priekulu novads", Name="Priekulu novads", Type="Municipality" },
            new(){ Code ="76", LocalName="Raunas novads", Name="Raunas novads", Type="Municipality" },
            new(){ Code ="77", LocalName="Rezeknes novads", Name="Rezeknes novads", Type="Municipality" },
            new(){ Code ="78", LocalName="Riebinu novads", Name="Riebinu novads", Type="Municipality" },
            new(){ Code ="79", LocalName="Rojas novads", Name="Rojas novads", Type="Municipality" },
            new(){ Code ="80", LocalName="Ropau novads", Name="Ropau novads", Type="Municipality" },
            new(){ Code ="81", LocalName="Rucavas novads", Name="Rucavas novads", Type="Municipality" },
            new(){ Code ="82", LocalName="Rugaju novads", Name="Rugaju novads", Type="Municipality" },
            new(){ Code ="84", LocalName="Rujienas novads", Name="Rujienas novads", Type="Municipality" },
            new(){ Code ="83", LocalName="Rundales novads", Name="Rundales novads", Type="Municipality" },
            new(){ Code ="86", LocalName="Salacgrivas novads", Name="Salacgrivas novads", Type="Municipality" },
            new(){ Code ="85", LocalName="Salas novads", Name="Salas novads", Type="Municipality" },
            new(){ Code ="87", LocalName="Salaspils novads", Name="Salaspils novads", Type="Municipality" },
            new(){ Code ="88", LocalName="Saldus novads", Name="Saldus novads", Type="Municipality" },
            new(){ Code ="89", LocalName="Saulkrastu novads", Name="Saulkrastu novads", Type="Municipality" },
            new(){ Code ="90", LocalName="Sejas novads", Name="Sejas novads", Type="Municipality" },
            new(){ Code ="91", LocalName="Siguldas novads", Name="Siguldas novads", Type="Municipality" },
            new(){ Code ="92", LocalName="Skriveru novads", Name="Skriveru novads", Type="Municipality" },
            new(){ Code ="93", LocalName="Skrundas novads", Name="Skrundas novads", Type="Municipality" },
            new(){ Code ="94", LocalName="Smiltenes novads", Name="Smiltenes novads", Type="Municipality" },
            new(){ Code ="95", LocalName="Stopinu novads", Name="Stopinu novads", Type="Municipality" },
            new(){ Code ="96", LocalName="Strencu novads", Name="Strencu novads", Type="Municipality" },
            new(){ Code ="97", LocalName="Talsu novads", Name="Talsu novads", Type="Municipality" },
            new(){ Code ="98", LocalName="Tervetes novads", Name="Tervetes novads", Type="Municipality" },
            new(){ Code ="99", LocalName="Tukuma novads", Name="Tukuma novads", Type="Municipality" },
            new(){ Code ="100", LocalName="Vainodes novads", Name="Vainodes novads", Type="Municipality" },
            new(){ Code ="101", LocalName="Valkas novads", Name="Valkas novads", Type="Municipality" },
            new(){ Code ="102", LocalName="Varaklanu novads", Name="Varaklanu novads", Type="Municipality" },
            new(){ Code ="103", LocalName="Varkavas novads", Name="Varkavas novads", Type="Municipality" },
            new(){ Code ="105", LocalName="Vecumnieku novads", Name="Vecumnieku novads", Type="Municipality" },
            new(){ Code ="106", LocalName="Ventspils novads", Name="Ventspils novads", Type="Municipality" },
            new(){ Code ="107", LocalName="Viesites novads", Name="Viesites novads", Type="Municipality" },
            new(){ Code ="108", LocalName="Vilakas novads", Name="Vilakas novads", Type="Municipality" },
            new(){ Code ="109", LocalName="Vilanu novads", Name="Vilanu novads", Type="Municipality" },
            new(){ Code ="110", LocalName="Zilupes novads", Name="Zilupes novads", Type="Municipality" }

        });
    }
}
