using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsMT()
    {
        AddSubdivisions("MT", new List<Subdivision>()
        {
            new(){ Code ="1", LocalName="Attard", Name="Attard", Type="LocalCouncil" },
            new(){ Code ="2", LocalName="Balzan", Name="Balzan", Type="LocalCouncil" },
            new(){ Code ="3", LocalName="Birgu", Name="Birgu", Type="LocalCouncil" },
            new(){ Code ="4", LocalName="Birkirkara", Name="Birkirkara", Type="LocalCouncil" },
            new(){ Code ="5", LocalName="Birzebbuga", Name="Birzebbuga", Type="LocalCouncil" },
            new(){ Code ="6", LocalName="Bormla", Name="Bormla", Type="LocalCouncil" },
            new(){ Code ="7", LocalName="Dingli", Name="Dingli", Type="LocalCouncil" },
            new(){ Code ="8", LocalName="Fgura", Name="Fgura", Type="LocalCouncil" },
            new(){ Code ="9", LocalName="Floriana", Name="Floriana", Type="LocalCouncil" },
            new(){ Code ="10", LocalName="Fontana", Name="Fontana", Type="LocalCouncil" },
            new(){ Code ="13", LocalName="Ghajnsielem", Name="Ghajnsielem", Type="LocalCouncil" },
            new(){ Code ="14", LocalName="Gharb", Name="Gharb", Type="LocalCouncil" },
            new(){ Code ="15", LocalName="Gharghur", Name="Gharghur", Type="LocalCouncil" },
            new(){ Code ="16", LocalName="Ghasri", Name="Ghasri", Type="LocalCouncil" },
            new(){ Code ="17", LocalName="Ghaxaq", Name="Ghaxaq", Type="LocalCouncil" },
            new(){ Code ="11", LocalName="Gudja", Name="Gudja", Type="LocalCouncil" },
            new(){ Code ="12", LocalName="Gzira", Name="Gzira", Type="LocalCouncil" },
            new(){ Code ="18", LocalName="Hamrun", Name="Hamrun", Type="LocalCouncil" },
            new(){ Code ="19", LocalName="Iklin", Name="Iklin", Type="LocalCouncil" },
            new(){ Code ="20", LocalName="Isla", Name="Isla", Type="LocalCouncil" },
            new(){ Code ="21", LocalName="Kalkara", Name="Kalkara", Type="LocalCouncil" },
            new(){ Code ="22", LocalName="Kercem", Name="Kercem", Type="LocalCouncil" },
            new(){ Code ="23", LocalName="Kirkop", Name="Kirkop", Type="LocalCouncil" },
            new(){ Code ="24", LocalName="Lija", Name="Lija", Type="LocalCouncil" },
            new(){ Code ="25", LocalName="Luqa", Name="Luqa", Type="LocalCouncil" },
            new(){ Code ="26", LocalName="Marsa", Name="Marsa", Type="LocalCouncil" },
            new(){ Code ="27", LocalName="Marsaskala", Name="Marsaskala", Type="LocalCouncil" },
            new(){ Code ="28", LocalName="Marsaxlokk", Name="Marsaxlokk", Type="LocalCouncil" },
            new(){ Code ="29", LocalName="Mdina", Name="Mdina", Type="LocalCouncil" },
            new(){ Code ="30", LocalName="Mellieha", Name="Mellieha", Type="LocalCouncil" },
            new(){ Code ="31", LocalName="Mgarr", Name="Mgarr", Type="LocalCouncil" },
            new(){ Code ="32", LocalName="Mosta", Name="Mosta", Type="LocalCouncil" },
            new(){ Code ="33", LocalName="Mqabba", Name="Mqabba", Type="LocalCouncil" },
            new(){ Code ="34", LocalName="Msida", Name="Msida", Type="LocalCouncil" },
            new(){ Code ="35", LocalName="Mtarfa", Name="Mtarfa", Type="LocalCouncil" },
            new(){ Code ="36", LocalName="Munxar", Name="Munxar", Type="LocalCouncil" },
            new(){ Code ="37", LocalName="Nadur", Name="Nadur", Type="LocalCouncil" },
            new(){ Code ="38", LocalName="Naxxar", Name="Naxxar", Type="LocalCouncil" },
            new(){ Code ="39", LocalName="Paola", Name="Paola", Type="LocalCouncil" },
            new(){ Code ="40", LocalName="Pembroke", Name="Pembroke", Type="LocalCouncil" },
            new(){ Code ="41", LocalName="Pietà", Name="Pietà", Type="LocalCouncil" },
            new(){ Code ="42", LocalName="Qala", Name="Qala", Type="LocalCouncil" },
            new(){ Code ="43", LocalName="Qormi", Name="Qormi", Type="LocalCouncil" },
            new(){ Code ="44", LocalName="Qrendi", Name="Qrendi", Type="LocalCouncil" },
            new(){ Code ="45", LocalName="Rabat Gozo", Name="Rabat Gozo", Type="LocalCouncil" },
            new(){ Code ="46", LocalName="Rabat Malta", Name="Rabat Malta", Type="LocalCouncil" },
            new(){ Code ="47", LocalName="Safi", Name="Safi", Type="LocalCouncil" },
            new(){ Code ="49", LocalName="Saint John", Name="Saint John", Type="LocalCouncil" },
            new(){ Code ="48", LocalName="Saint Julian's", Name="Saint Julian's", Type="LocalCouncil" },
            new(){ Code ="50", LocalName="Saint Lawrence", Name="Saint Lawrence", Type="LocalCouncil" },
            new(){ Code ="53", LocalName="Saint Lucia's", Name="Saint Lucia's", Type="LocalCouncil" },
            new(){ Code ="51", LocalName="Saint Paul's Bay", Name="Saint Paul's Bay", Type="LocalCouncil" },
            new(){ Code ="52", LocalName="Sannat", Name="Sannat", Type="LocalCouncil" },
            new(){ Code ="54", LocalName="Santa Venera", Name="Santa Venera", Type="LocalCouncil" },
            new(){ Code ="55", LocalName="Siggiewi", Name="Siggiewi", Type="LocalCouncil" },
            new(){ Code ="56", LocalName="Sliema", Name="Sliema", Type="LocalCouncil" },
            new(){ Code ="57", LocalName="Swieqi", Name="Swieqi", Type="LocalCouncil" },
            new(){ Code ="58", LocalName="Ta' Xbiex", Name="Ta' Xbiex", Type="LocalCouncil" },
            new(){ Code ="59", LocalName="Tarxien", Name="Tarxien", Type="LocalCouncil" },
            new(){ Code ="60", LocalName="Valletta", Name="Valletta", Type="LocalCouncil" },
            new(){ Code ="61", LocalName="Xaghra", Name="Xaghra", Type="LocalCouncil" },
            new(){ Code ="62", LocalName="Xewkija", Name="Xewkija", Type="LocalCouncil" },
            new(){ Code ="63", LocalName="Xghajra", Name="Xghajra", Type="LocalCouncil" },
            new(){ Code ="64", LocalName="Zabbar", Name="Zabbar", Type="LocalCouncil" },
            new(){ Code ="65", LocalName="Zebbug Gozo", Name="Zebbug Gozo", Type="LocalCouncil" },
            new(){ Code ="66", LocalName="Zebbug Malta", Name="Zebbug Malta", Type="LocalCouncil" },
            new(){ Code ="67", LocalName="Zejtun", Name="Zejtun", Type="LocalCouncil" },
            new(){ Code ="68", LocalName="Zurrieq", Name="Zurrieq", Type="LocalCouncil" }

        });
    }
}
