using AngryMonkey.Cloud.Geography;
namespace AngryMonkey.Cloud;

public partial class CloudGeographyClient
{
    private static void FillInSubdivisionsTH()
    {
        AddSubdivisions("TH", new List<Subdivision>()
        {
            new(){ Code ="37", LocalName="Amnat Charoen", Name="Amnat Charoen", Type="Province" },
            new(){ Code ="15", LocalName="Ang Thong", Name="Ang Thong", Type="Province" },
            new(){ Code ="38", LocalName="Bueng Kan", Name="Bueng Kan", Type="Province" },
            new(){ Code ="31", LocalName="Buri Ram", Name="Buri Ram", Type="Province" },
            new(){ Code ="24", LocalName="Chachoengsao", Name="Chachoengsao", Type="Province" },
            new(){ Code ="18", LocalName="Chai Nat", Name="Chai Nat", Type="Province" },
            new(){ Code ="36", LocalName="Chaiyaphum", Name="Chaiyaphum", Type="Province" },
            new(){ Code ="22", LocalName="Chanthaburi", Name="Chanthaburi", Type="Province" },
            new(){ Code ="50", LocalName="Chiang Mai", Name="Chiang Mai", Type="Province" },
            new(){ Code ="57", LocalName="Chiang Rai", Name="Chiang Rai", Type="Province" },
            new(){ Code ="20", LocalName="Chon Buri", Name="Chon Buri", Type="Province" },
            new(){ Code ="86", LocalName="Chumphon", Name="Chumphon", Type="Province" },
            new(){ Code ="46", LocalName="Kalasin", Name="Kalasin", Type="Province" },
            new(){ Code ="62", LocalName="Kamphaeng Phet", Name="Kamphaeng Phet", Type="Province" },
            new(){ Code ="71", LocalName="Kanchanaburi", Name="Kanchanaburi", Type="Province" },
            new(){ Code ="40", LocalName="Khon Kaen", Name="Khon Kaen", Type="Province" },
            new(){ Code ="81", LocalName="Krabi", Name="Krabi", Type="Province" },
            new(){ Code ="10", LocalName="Krung Thep Maha Nakhon", Name="Krung Thep Maha Nakhon", Type="MetropolitanAdministration" },
            new(){ Code ="52", LocalName="Lampang", Name="Lampang", Type="Province" },
            new(){ Code ="51", LocalName="Lamphun", Name="Lamphun", Type="Province" },
            new(){ Code ="42", LocalName="Loei", Name="Loei", Type="Province" },
            new(){ Code ="16", LocalName="Lop Buri", Name="Lop Buri", Type="Province" },
            new(){ Code ="58", LocalName="Mae Hong Son", Name="Mae Hong Son", Type="Province" },
            new(){ Code ="44", LocalName="Maha Sarakham", Name="Maha Sarakham", Type="Province" },
            new(){ Code ="49", LocalName="Mukdahan", Name="Mukdahan", Type="Province" },
            new(){ Code ="26", LocalName="Nakhon Nayok", Name="Nakhon Nayok", Type="Province" },
            new(){ Code ="73", LocalName="Nakhon Pathom", Name="Nakhon Pathom", Type="Province" },
            new(){ Code ="48", LocalName="Nakhon Phanom", Name="Nakhon Phanom", Type="Province" },
            new(){ Code ="30", LocalName="Nakhon Ratchasima", Name="Nakhon Ratchasima", Type="Province" },
            new(){ Code ="60", LocalName="Nakhon Sawan", Name="Nakhon Sawan", Type="Province" },
            new(){ Code ="80", LocalName="Nakhon Si Thammarat", Name="Nakhon Si Thammarat", Type="Province" },
            new(){ Code ="55", LocalName="Nan", Name="Nan", Type="Province" },
            new(){ Code ="96", LocalName="Narathiwat", Name="Narathiwat", Type="Province" },
            new(){ Code ="39", LocalName="Nong Bua Lam Phu", Name="Nong Bua Lam Phu", Type="Province" },
            new(){ Code ="43", LocalName="Nong Khai", Name="Nong Khai", Type="Province" },
            new(){ Code ="12", LocalName="Nonthaburi", Name="Nonthaburi", Type="Province" },
            new(){ Code ="13", LocalName="Pathum Thani", Name="Pathum Thani", Type="Province" },
            new(){ Code ="94", LocalName="Pattani", Name="Pattani", Type="Province" },
            new(){ Code ="82", LocalName="Phangnga", Name="Phangnga", Type="Province" },
            new(){ Code ="93", LocalName="Phatthalung", Name="Phatthalung", Type="Province" },
            new(){ Code ="56", LocalName="Phayao", Name="Phayao", Type="Province" },
            new(){ Code ="67", LocalName="Phetchabun", Name="Phetchabun", Type="Province" },
            new(){ Code ="76", LocalName="Phetchaburi", Name="Phetchaburi", Type="Province" },
            new(){ Code ="66", LocalName="Phichit", Name="Phichit", Type="Province" },
            new(){ Code ="65", LocalName="Phitsanulok", Name="Phitsanulok", Type="Province" },
            new(){ Code ="14", LocalName="Phra Nakhon Si Ayutthaya", Name="Phra Nakhon Si Ayutthaya", Type="Province" },
            new(){ Code ="54", LocalName="Phrae", Name="Phrae", Type="Province" },
            new(){ Code ="83", LocalName="Phuket", Name="Phuket", Type="Province" },
            new(){ Code ="25", LocalName="Prachin Buri", Name="Prachin Buri", Type="Province" },
            new(){ Code ="77", LocalName="Prachuap Khiri Khan", Name="Prachuap Khiri Khan", Type="Province" },
            new(){ Code ="85", LocalName="Ranong", Name="Ranong", Type="Province" },
            new(){ Code ="70", LocalName="Ratchaburi", Name="Ratchaburi", Type="Province" },
            new(){ Code ="21", LocalName="Rayong", Name="Rayong", Type="Province" },
            new(){ Code ="45", LocalName="Roi Et", Name="Roi Et", Type="Province" },
            new(){ Code ="27", LocalName="Sa Kaeo", Name="Sa Kaeo", Type="Province" },
            new(){ Code ="47", LocalName="Sakon Nakhon", Name="Sakon Nakhon", Type="Province" },
            new(){ Code ="11", LocalName="Samut Prakan", Name="Samut Prakan", Type="Province" },
            new(){ Code ="74", LocalName="Samut Sakhon", Name="Samut Sakhon", Type="Province" },
            new(){ Code ="75", LocalName="Samut Songkhram", Name="Samut Songkhram", Type="Province" },
            new(){ Code ="19", LocalName="Saraburi", Name="Saraburi", Type="Province" },
            new(){ Code ="91", LocalName="Satun", Name="Satun", Type="Province" },
            new(){ Code ="33", LocalName="Si Sa Ket", Name="Si Sa Ket", Type="Province" },
            new(){ Code ="17", LocalName="Sing Buri", Name="Sing Buri", Type="Province" },
            new(){ Code ="90", LocalName="Songkhla", Name="Songkhla", Type="Province" },
            new(){ Code ="64", LocalName="Sukhothai", Name="Sukhothai", Type="Province" },
            new(){ Code ="72", LocalName="Suphan Buri", Name="Suphan Buri", Type="Province" },
            new(){ Code ="84", LocalName="Surat Thani", Name="Surat Thani", Type="Province" },
            new(){ Code ="32", LocalName="Surin", Name="Surin", Type="Province" },
            new(){ Code ="63", LocalName="Tak", Name="Tak", Type="Province" },
            new(){ Code ="92", LocalName="Trang", Name="Trang", Type="Province" },
            new(){ Code ="23", LocalName="Trat", Name="Trat", Type="Province" },
            new(){ Code ="34", LocalName="Ubon Ratchathani", Name="Ubon Ratchathani", Type="Province" },
            new(){ Code ="41", LocalName="Udon Thani", Name="Udon Thani", Type="Province" },
            new(){ Code ="61", LocalName="Uthai Thani", Name="Uthai Thani", Type="Province" },
            new(){ Code ="53", LocalName="Uttaradit", Name="Uttaradit", Type="Province" },
            new(){ Code ="95", LocalName="Yala", Name="Yala", Type="Province" },
            new(){ Code ="35", LocalName="Yasothon", Name="Yasothon", Type="Province" }

        });
    }
}
